### ISSUE TITLE
Daily Work GAG 13/03/2023

### ISSUE THREAD

**Issue by kosmoGAG** [kosmoGAG/Daily#1]
# Plan de trabajo
Nombre: Guillermo Garcia Perea
Fecha: 13/03/2023
Hora de entrada: 6:00am (Colombia)
### ToDo General

- [ ] Revisar estructura de la base de datos Kosmetikon lab
- [ ] Definir estructura de solicitudes http para búsqueda en kosmetikon lab
- [ ] Definir nuevas tablas necesarias para la búsqueda
- [ ] Crear estructura inicial de las tablas de búsqueda 
- [ ] Crear endpoints que serán utilizados en el módulo de búsqueda 
- [ ] Probar los diferentes endpoints creados usando algún cliente http 
- [ ] Crear un nuevo componente para la búsqueda en la aplicación frontend de kosmetikon lab
- [ ] Desarrollar el diseño básico del componente 
- [ ] Conectar el frontend con los endpoints de búsqueda en el backend 

### ToDo del día 

- [ ] Revisar estructura de la base de datos Kosmetikon lab
- [ ] Definir estructura de solicitudes http para búsqueda en kosmetikon lab
- [ ] Definir nuevas tablas necesarias para la búsqueda
- [ ] Crear estructura inicial de las tablas de búsqueda 
- [ ] Crear endpoints que serán utilizados en el módulo de búsqueda 
- [ ] Probar los diferentes endpoints creados usando algún cliente http 

### Inacabados del día
